--left_lane_near_obstacle_speed_km_h=40
--left_lane_near_obstacle_display_dis=50

--left_lane_far_obstacle_speed_km_h=40
--left_lane_far_obstacle_display_dis=30

--front_obstacle_obstacle_speed_km_h=30
--front_obstacle_display_dis=60

--right_lane_far_obstacle_display_dis=50
--right_lane_far_obstacle_speed_km_h=15

--right_lane_near_obstacle_display_dis=-180
--right_lane_near_obstacle_speed_km_h=50

--random_obstacle_min_speed_km_h=70
--random_obstacle_max_speed_km_h=120
--obstacle_number=20
