/*
 * Copyright (c) TL Technologies Co., Ltd. 2019-2021. All rights reserved.
 * Description:  planning path static obs processor
 * Author: ROC
 */

#pragma once

#include <algorithm>
#include <functional>
#include <limits>
#include <memory>
#include <set>
#include <string>
#include <tuple>
#include <type_traits>
#include <unordered_map>
#include <utility>
#include <vector>

#include "planning/common/dependency_injector.h"
#include "planning/common/reference_line_info.h"
#include "planning/tasks/deciders/path_bounds_decider/bound_processor/process_bound.h"
#include "planning/tasks/deciders/path_bounds_decider/obs_processor/dynamic_buffer_processor.h"
#include "planning/tasks/deciders/path_bounds_decider/obs_processor/obs_processor.h"
#include "planning/tasks/deciders/path_bounds_decider/util/path_info.h"

namespace TL {
namespace planning {

class ObsStaticProcessor : public ObsProcessor {
 public:
  ObsStaticProcessor(const std::shared_ptr<DependencyInjector>& injector,
                     const TaskConfig& config);
  ~ObsStaticProcessor() override = default;

  /**
     * @brief Refine the boundary based on static obstacles. It will make sure
     *   the boundary doesn't contain any static obstacle so that the path
     *   generated by optimizer won't collide with any static obstacle.
     * @param reference_line_info 
     * @param frame 
     * @param path_boundaries 
     * @param blocking_obstacle_id 
     * @param towing_points
     * @param is_enable_towing_process
     * @return true 
     * @return false ,no condition to return false.
     */
  bool Process(ReferenceLineInfo* reference_line_info, Frame* frame,
               PathBound* path_boundaries, std::string* blocking_obstacle_id,
               TowingPointsInfo* towing_points,
               bool is_enable_towing_process) override;

  /** @brief Update the path_boundary at "idx", as well as the new center-line.
   *         It also checks if ADC is blocked (lmax < lmin).
   *  @param idx: The current index of the path_bounds
   *  @param left_bound: The minimum left boundary (l_max)
   *  @param right_bound: The maximum right boundary (l_min)
   *  @param path_boundaries: The path_boundaries (its content at idx will be updated)
   *  @param center_line: The center_line (to be updated)
   *  @return reference_line_info: If path is good, true; if path is blocked, false.
   */
  bool UpdatePathBoundaryAndCenterLineWithBuffer(
      size_t idx, double left_bound, double right_bound,
      std::vector<std::tuple<double, double, double>>* path_boundaries,
      double* center_line, const ReferenceLineInfo& reference_line_info);

  /**
    * @brief sort the static obstacles before adc
    *        sorted regulation :
    *            sort with s ,small to large 
    *            if s are equal , start s first.
    * 
    * @param indexed_obstacles: a list for all obstacles
    * @return std::vector<ObstacleEdge>: static obstacles already sorted
    */
  void SortObstaclesForSweepLine(
      const ReferenceLineInfo& reference_line_info,
      const IndexedList<std::string, Obstacle>& indexed_obstacles);

  /**
    * @brief filter the considered static obstacle
    * 
    * @param obstacle
    * @return true
    * @return false
    */
  bool IsConsiderStaticObstacle(const Obstacle* obstacle);

  /**
   * @brief Sort Static Obstacle Edges
   * 
   * @param prepare_to_sort_edges 
*/
  static void ForObstacleEdgesSort(
      std::vector<ObstacleEdge>* prepare_to_sort_edges);

  /**
   * @brief Set the Static Obstacle Bound Debug Info object
   * 
   * @param curr_obs_edge 
   */
  void SetStaticObstacleBoundDebugInfo(const ObstacleEdge& curr_obs_edge);

  /**
   * @brief calculate static obstacle towing prepare distance
   * 
   * @param sorted_obstacles 
   * @param curr_obs_edges
   * @param default_towing_prepare_distance
   * @param towing_prepare_distance
   * @param obs_idx
  */
  static bool CalculateStaticTowingPrepareDistance(
      const std::vector<ObstacleEdge>& sorted_obstacles,
      const std::pair<double, double>& curr_obs_edges,
      const std::pair<double, double>& default_towing_prepare_distance,
      std::pair<double, double>* towing_prepare_distance, size_t obs_idx);

  /**
   * @brief whether the distance between boundaries is too close to pass,
   *        considering both lateral and longitude
   * 
   * @param path_boundaries 
   * @param min_diff_bounds_idx: if too close,update the index as the trim point of boundary,
   *        otherwise, return -1;
   * @return true: is too close
   * @return false: not too close
   */
  bool IsMinDiffLeftAndRightBounds(const PathBound* path_boundaries,
                                   int* min_diff_bounds_idx);

  /**
  * @brief calculate the lateral boundary occupied by the obstacle
  * 
  * @param reference_point current reference point 
  * @param obs obstacle
  * @param obs_path_bound the lateral boundary occupied by the obstacle {l_min,l_max}
  * @param kinematic_corner first:kinematic_corner(x,y), second: whether has kinematic_corner
  * @return true: has effective obstacle bound
  */
  bool GetStaticObstacleBound(const ReferencePoint& reference_point,
                              const Obstacle& obs,
                              std::pair<double, double>* obs_path_bound,
                              const std::pair<Vec2d, bool>& kinematic_corner);

  /**
  * @brief calculate the Kinematic Corner of static obstacles
  * 
  * @param sorted_obstacles static obstatcles after filter and sorting 
  * @param indexed_obstacles all the obstacles
  * @param obs_kinematic_corner the result of calculation to kinematic_corner
  */
  bool GetObstacleKinematicCorner(
      std::vector<ObstacleEdge>* sorted_obstacles,
      const IndexedObstacles& indexed_obstacles,
      std::unordered_map<std::string, std::pair<Vec2d, bool>>*
          obs_kinematic_corner);

  /**
  * @brief calculate cross points
  * 
  * @param obs_corners 
  * @param cross_points
  * @param is_left_nudge
  */
  bool CalculateCrossPoints(
      std::vector<Vec2d>* obs_corners,
      std::vector<std::tuple<double, Vec2d, Vec2d>>* cross_points,
      bool is_left_nudge);

  /**
  * @brief set kinematic corner global point
  * 
  * @param cross_points
  * @param kinematic_corner_global_point
  * @param is_left_nudge
  */
  bool SetKinematicCornerGlobalPoint(
      const std::vector<std::tuple<double, Vec2d, Vec2d>>& cross_points,
      Vec2d* kinematic_corner_global_point, bool is_left_nudge);

  /**
  * @brief compare regular for tuple
  * 
  * @param a 
  * @param b 
  * @return true: a<b
  * @return false: a>=b
  */
  static bool TupleComp(const std::tuple<double, Vec2d, Vec2d>& a,
                        const std::tuple<double, Vec2d, Vec2d>& b);

  const std::vector<ObstacleEdge>& GetObstacleEdges() const {
    return obstacle_edges_;
  }

  const std::vector<ObstacleEdge>& GetNeedNudgeObstacleEdges() const {
    return need_nudge_obstacle_edges_;
  }

 private:
  DynamicBufferProcessor static_obs_dynamic_buffer_calculate_;
  std::vector<ObstacleEdge> obstacle_edges_;
  std::vector<ObstacleEdge> need_nudge_obstacle_edges_;
};
}  // namespace planning
}  // namespace TL
