
#prediction
--prediction_conf_file=conf/prediction/prediction_current_conf.pb.txt
--prediction_adapter_config_filename=conf/prediction/adapter.conf
--torch_vehicle_cruise_go_file=data/model/cruise_go_vehicle_model.pt
--torch_vehicle_cruise_cutin_file=data/model/cruise_cutin_vehicle_model.pt
# --evaluator_vehicle_tnt_file=data/model/tnt.onnx
--lane_search_radius=5.0
--prediction_trajectory_time_length_pre_freemove=4.0
--enable_prediction_output
# --adjust_velocity_by_obstacle_heading
--lane_sequence_threshold_cruise=0.55
--lane_sequence_threshold_junction=0.60
--go_approach_rate=0.995
--cutin_approach_rate=0.98
--trajectory_time_min_interval=0.1
--enable_online_record4Prediction=false
--max_num_dump_feature=10000
--enable_multi_thread=false
--vehicle_max_linear_acc=3.0
--vehicle_min_linear_acc=-5.0
--vehicle_max_linear_acc_freemove=0.5
--vehicle_min_linear_acc_freemove=-0.5
--prediction_trajectory_time_length=8.0
--prediction_trajectory_time_length_freemove=3.0
--default_time_to_lat_end_state=5.0
--scan_length=400.0
--scan_width=40.0
--max_num_obstacles=150
--max_angle_diff_to_adjust_velocity=0.03
--max_lane_angle_diff=0.785398
--default_lateral_approach_speed=0.05
--enable_lane_sequence_acc
--max_num_lane_point=1
--target_lane_gap=20.0
--road_distance=150
--point_distance=5.0
--road_graph_max_search_horizon=40
--converged_scale=1.0
--unconverged_scale=5.0
--cost_max_adjustment=0.0
--cost_min_adjustment=-0.2
--lane_change_dist=7.0
--intrusion_width_ratio=0.0
--dist_obs2merge_lane=50.0
--obs_id_for_dbn_debug=-1
--still_bicycle_speed_threshold=1.0
--still_pedestrian_speed_threshold=0.2
--max_lane_angle_diff_in_junction=0.261799
--prediction_debug_history_frame_num=10
--save_routing_lane_ids=true
--enable_perception_sensor_filter=false
