--flagfile=conf/global_flagfile.txt
#--control_conf_file=conf/control_conf.pb.txt
--control_conf_file=conf/control/mpc_controller_conf.pb.txt
--enable_speed_station_preview=true
--enable_interpolation_by_time=false
--use_preview_speed_for_table=false
--enable_gain_scheduler=true
--set_steer_limit=true
--enable_slope_offset=false
--enable_maximum_steer_rate_limit

--state_transform_to_com_reverse=true
--state_transform_to_com_drive=true
--trajectory_transform_to_com_reverse=true
--trajectory_transform_to_com_drive=true
--enable_feedback_augment_on_high_speed=false
# --reverse_heading_vehicle_state=false
# --reverse_heading_control=false

--query_time_nearest_point_only=false
--query_forward_time_point_only=false
# --use_control_submodules=true
--enable_csv_debug
--control_delay_compensation=0.2
--steer_angle_limit=1.0
--steer_angle_limit_first=1.0
--enable_mpc_calibration=false

--enable_steer_2_torque=true
--enable_pid_speedsegment_control=false
--enable_steer_segment_feedforward=true
--enable_torque_gradient_protection=true
--steer_2_torque_right= 1.0
--steer_2_torque_left=1.0

# teleop
#--enable_teleop
--enable_teleop_pid_calculate = false
--enable_teleop_steer_torque = true

# mbd control conf
--enable_mbd_control=true
--mbd_control_conf_file=conf/control/mbd_control_conf.pb.txt
--mbd_control_outcmd_normalize=true
# test mode gear command 1-D, 2-R
--lonctrl_api_gearcmd=1
--mbd_control_log_debug=true
--use_localization_timestamp_for_control=false
--set_localization_control_time_gap=0.1