/*
 * Copyright (c) TL auto Co., Ltd. 2021-2022. All rights reserved.
 */

#pragma once

#include <deque>
#include <list>
#include <memory>
#include <string>
#include <tuple>
#include <unordered_map>
#include <utility>
#include <vector>

#include "common/vehicle_state/vehicle_state_provider.h"
#include "planning/localview/lane_line_builder/navigation_hdmap_lane_line/lanemarker_new_decider/decider_data.h"
#include "planning/localview/lane_line_builder/navigation_hdmap_lane_line/navigation_lanecentral_constructor.h"

#include "planning/localview/lane_line_builder/navigation_hdmap_lane_line/lanemarker_new_decider/lane_line_delay.h"
#include "planning/pnc_map/pnc_map.h"
#include "planning/proto/navigation_hdmap_config.pb.h"
#include "proto/common/vehicle_state.pb.h"
#include "proto/map/navigation.pb.h"

/**
 * @namespace TL::navigation_hdmap
 * @brief TL::navigation_hdmap
 */
namespace TL {
namespace planning {
using TL::common::math::Vec2d;
using TL::planning::lanelineprocess::LneWdeValid;

// A navigation path tuple.
//
// first element: original navigation line index of the current navigation path.
// A negative value indicates illegal.
//
// second element: half of the lateral distance to the left adjacent navigation
// path, that is, the left width of the lane generated by this navigation path.
// If the navigation path is generated based on lane markers, the value is the
// perceived left lane width. If there is no left adjacent navigation path, the
// value is "default_left_width_". A negative value indicates illegal.
//
// third element: half of the lateral distance to the right adjacent navigation
// path, that is, the right width of the lane generated by this navigation path.
// If the navigation path is generated based on lane markers, the value is the
// perceived right lane width. If there is no right adjacent navigation path,
// the value is "default_right_width_". A negative value indicates illegal.
//
// fourth element : a shared pointer of the current navigation path.
using NaviPathTuple =
    std::tuple<int, std::vector<double>, std::vector<double>,
               std::shared_ptr<navigation_hdmap::NavigationPath>,
               std::shared_ptr<hdmap::LineSegment>,
               std::shared_ptr<hdmap::LineSegment>,
               std::pair<TL::hdmap::LaneBoundaryType_Type,
                         TL::hdmap::LaneBoundaryType_Type>>;

class NavigationLanePathGenerator {
 public:
  NavigationLanePathGenerator() = default;
  explicit NavigationLanePathGenerator(
      const planning::PerceptionMapConfig& config);
  ~NavigationLanePathGenerator() = default;

  /**
   * @brief Set the configuration information required by the
   * `NavigationLanePathGenerator`.
   * @param config Configuration object.
   * @return None.
   */
  TL::common::Status Init();

  void SetVehicleState(
      const std::shared_ptr<const common::VehicleState>& vehicle_state);

  /**
   * @brief Generate a lane centerline from the perceived lane markings and
   * convert it to a navigation line segment.
   * @param lane_marker The perceived lane markings.
   * @param path The converted navigation line segment.
   * @param is_mobileye  Whether the data source comes from the mobileye.
   * @return None.
   */
  Status ConvertLaneMarkerToPath(
      const perception::LaneMarkers& lane_marker,
      std::unordered_map<std::string, std::vector<Vec2d>>* lane_marker_points,
      std::list<NaviPathTuple>* navigation_path_list, LneWdeValid lane_width);

 private:
  /**
   * @brief Calculate the curvature value based on the cubic polynomial's
   * coefficients and an independent variable.
   * @param c1 Cubic polynomial coefficient.
   * @param c2 Cubic polynomial coefficient.
   * @param c3 Cubic polynomial coefficient.
   * @param x Independent variable.
   * @return Calculated curvature value.
   */
  static double GetKappa(double c1, double c2, double c3, double x);

  double ComputeLaneWidth(double* leftwidth);

  void TranslatedReferenceLine(const perception::LaneMarkers& lane_marker,
                               const std::vector<Vec2d>& ref_line_point,
                               common::Path* path,
                               const std::vector<Vec2d>& left_line_point,
                               const std::vector<Vec2d>& right_line_point,
                               hdmap::LineSegment* left_path,
                               hdmap::LineSegment* right_path);
  void BoundaryLineBus2Earth(const std::vector<Vec2d>& line_point,
                             hdmap::LineSegment* path);

 private:
  static void CalculateLaneWidth(const std::vector<Vec2d>& left_line_point,
                                 const std::vector<Vec2d>& right_line_point,
                                 const std::vector<Vec2d>& cetral_line_point,
                                 std::vector<double>* left_line_width,
                                 std::vector<double>* right_line_width);
  static void CutNexLaneLength(std::vector<Vec2d>* left_line_point,
                               std::vector<Vec2d>* right_line_point,
                               std::vector<Vec2d>* central_line_point,
                               std::vector<double>* left_line_width,
                               std::vector<double>* right_line_width,
                               double* history_lane_length);

  static double LaneWidthAverage(int lane_width_valid, double lane_width,
                                 std::deque<double>* lane_width_dq);
  //   void GetCentralLaneFitLanemarker(
  //       const double view_range, const std::vector<Vec2d>& cetral_line_point,
  //       perception::LaneMarker* const central_lanemarker);
  // the configuration information required by the `NavigationLanePathGenerator
  planning::PerceptionMapConfig config_;

  // when invalid, left_width_ < 0
  double perceived_left_width_ = -1.0;

  // when invalid, right_width_ < 0
  double perceived_right_width_ = -1.0;

  // The standard lane width of China's expressway is 3.75 meters.
  double default_left_width_ = 1.875;
  double default_right_width_ = 1.875;
  double history_left_lane_length_ = 0.0;
  double history_right_lane_length_ = 0.0;

  NaviLaneCentralConstructor navi_central_line_constructor_{};
  // left and right central line history
  std::shared_ptr<navigation_hdmap::NavigationPath>
      right_central_navi_path_history_ =
          std::make_shared<navigation_hdmap::NavigationPath>();
  std::shared_ptr<navigation_hdmap::NavigationPath>
      left_central_navi_path_history_ =
          std::make_shared<navigation_hdmap::NavigationPath>();
  std::shared_ptr<hdmap::LineSegment> right_boundary_of_rightlane_history_ =
      std::make_shared<hdmap::LineSegment>();
  std::shared_ptr<hdmap::LineSegment> left_boundary_of_leftlane_history_ =
      std::make_shared<hdmap::LineSegment>();

  std::vector<Vec2d> central_line_pts_{};
  std::vector<Vec2d> left_central_line_pts_{};
  std::vector<Vec2d> right_central_line_pts_{};

  std::shared_ptr<const common::VehicleState> vehicle_state_{nullptr};

  std::deque<double> current_lane_width_dq_{};
  std::deque<double> left_lane_width_dq_{};
  std::deque<double> right_lane_width_dq_{};
  lanelineprocess::Delay<double> current_lane_width_delay_;
  lanelineprocess::Delay<double> left_lane_width_delay_;
  lanelineprocess::Delay<double> right_lane_width_delay_;
};

}  // namespace planning
}  // namespace TL
