/*
 * Copyright (c) TL auto Co., Ltd. 2021-2022. All rights reserved.
 */

#pragma once

#include <deque>
#include <list>
#include <memory>
#include <string>
#include <tuple>
#include <unordered_map>
#include <utility>
#include <vector>

#include "common/filters/digital_filter.h"
#include "common/filters/digital_filter_coefficients.h"
#include "common/filters/mean_filter.h"
#include "common/status/status.h"
#include "planning/localview/lane_line_builder/navigation_hdmap_lane_line/lanemarker_old_decider/navigation_lanecentral_constructor.h"

#include "planning/proto/navigation_hdmap_config.pb.h"
#include "proto/common/vehicle_state.pb.h"
#include "proto/localization/localization.pb.h"
#include "proto/map/navigation.pb.h"
#include "proto/perception/perception_obstacle.pb.h"

// NOLINTBEGIN
/**
 * @namespace TL::navigation_hdmap
 * @brief TL::navigation_hdmap
 */
namespace TL {
namespace planning {
using TL::common::math::Vec2d;

// A navigation path tuple.
//
// first element: original navigation line index of the current navigation path.
// A negative value indicates illegal.
//
// second element: half of the lateral distance to the left adjacent navigation
// path, that is, the left width of the lane generated by this navigation path.
// If the navigation path is generated based on lane markers, the value is the
// perceived left lane width. If there is no left adjacent navigation path, the
// value is "default_left_width_". A negative value indicates illegal.
//
// third element: half of the lateral distance to the right adjacent navigation
// path, that is, the right width of the lane generated by this navigation path.
// If the navigation path is generated based on lane markers, the value is the
// perceived right lane width. If there is no right adjacent navigation path,
// the value is "default_right_width_". A negative value indicates illegal.
//
// fourth element : a shared pointer of the current navigation path.
typedef std::tuple<
    int, double, double, std::shared_ptr<navigation_hdmap::NavigationPath>,
    std::shared_ptr<hdmap::LineSegment>, std::shared_ptr<hdmap::LineSegment>>
    NaviPathTupleOld;

// typedef std::tuple<int, double, double,
// std::shared_ptr<navigation_hdmap::NavigationPath>>
//     NaviPathTuple;

// A stitching index pair.
// pair.first: the start stitching index of the current navigation line.
// pair.second: the end stitching index of the current navigation line.
typedef std::pair<int, int> StitchIndexPair;

// A projection index pair.
// pair.first: projection index of the vehicle in the current navigation line.
// pair.second: the distance between the vehicle's initial position and the
// projection position in the current navigation line.
typedef std::pair<int, double> ProjIndexPair;

/**
 * @class NavigationLaneMobileye
 * @brief NavigationLaneMobileye generates a real-time relative map based on
 * navagation lines.
 *
 * First, several navigation lines are received from the `NavigationInfo`
 * object;
 *
 * Second, several navigation line segments with the length of about 250 m are
 * cut from the whole navigation lines and the UTM coordinates are converted
 * into local coordinates with the current position of the vehicle as the
 * origin;
 *
 * Third, the navigation line segment of the vehicle's current lane is merged
 * with the perceived lane centerline.
 *
 * Fourth, a real-time relative map is dynamically created based on navigation
 * line segments and perceived lane width;
 *
 * Fifth, the relative map is output as a `MapMsg` object pointer.
 */
class NavigationLaneMobileye {
 public:
  NavigationLaneMobileye() = default;
  explicit NavigationLaneMobileye(const planning::PerceptionMapConfig& config);
  ~NavigationLaneMobileye() = default;

  /**
   * @brief Set the configuration information required by the
   * `NavigationLaneMobileye`.
   * @param config Configuration object.
   * @return None.
   */
  TL::common::Status Init();
  void SetConfig(const planning::PerceptionMapConfig& config);

  void SetVehicleState(
      const std::shared_ptr<const common::VehicleState>& vehicle_state);

  /**
   * @brief Set the default width of a lane.
   * @param left_width Left half width of a lane.
   * @param right_width Right half width of a lane.
   * @return None.
   */
  void SetDefaultWidth(const double left_width, const double right_width) {
    default_left_width_ = left_width;
    default_right_width_ = right_width;
  }

  /**
   * @brief Generate a suitable path (i.e. a navigation line segment).
   * @param
   * @return True if a suitable path is created; false otherwise.
   */
  bool GeneratePath();

  /**
   * @brief Update perceived lane line information.
   * @param lane_marker Perceived lane line information to be updated.
   * @return None.
   */
  void UpdateLaneMarker(const perception::LaneMarkers& lane_marker) {
    lane_marker_ = lane_marker;
  }

  /**
   * @brief Get the generated lane segment where the vehicle is currently
   * located.
   * @param
   * @return The generated lane segment where the vehicle is currently located.
   */
  navigation_hdmap::NavigationPath Path() const {
    const auto& current_navi_path = std::get<3>(current_navi_path_tuple_);
    if (current_navi_path) {
      return *current_navi_path;
    }
    return navigation_hdmap::NavigationPath();
  }

  /**
   * @brief Generate a real-time relative map of approximately 250 m in length
   * based on several navigation line segments and map generation configuration
   * information.
   * @param map_config Map generation configuration information.
   * @param map_msg A pointer which outputs the real-time relative map.
   * @return True if the real-time relative map is created; false otherwise.
   */
  bool CreateMap(navigation_hdmap::MapMsg* const map_msg);

 private:
  /**
   * @brief Create a single lane map.
   * @param navi_path_tuple A navigation path tuple.
   * @param map_config Map generation configuration information.
   * @param lane_marker The Perceived obstacle information and the lane
   * markings are used here.
   * @param hdmap The output single lane map in high-definition map format in
   * the relative map.
   * @param navigation_path The output navigation path map in the relative map.
   * @return True if the map is created; false otherwise.
   */
  bool CreateSingleLaneMap(
      const NaviPathTupleOld& navi_path_tuple,
      const perception::LaneMarkers& lane_marker, hdmap::Map* const hdmap,
      google::protobuf::Map<std::string,
                            navigation_hdmap::NavigationPath>* const
          navigation_path) const;

  /**
   * @brief Calculate the value of a cubic polynomial according to the given
   * coefficients and an independent variable.
   * @param c0 Cubic polynomial coefficient.
   * @param c1 Cubic polynomial coefficient.
   * @param c2 Cubic polynomial coefficient.
   * @param c3 Cubic polynomial coefficient.
   * @param x Independent variable.
   * @return Calculated value of the cubic polynomial.
   */
  double EvaluateCubicPolynomial(const double c0, const double c1,
                                 const double c2, const double c3,
                                 const double x) const;

  /**
   * @brief Calculate the curvature value based on the cubic polynomial's
   * coefficients and an independent variable.
   * @param c1 Cubic polynomial coefficient.
   * @param c2 Cubic polynomial coefficient.
   * @param c3 Cubic polynomial coefficient.
   * @param x Independent variable.
   * @return Calculated curvature value.
   */
  double GetKappa(const double c1, const double c2, const double c3,
                  const double x);

  /**
   * @brief Generate a lane centerline from the perceived lane markings and
   * convert it to a navigation line segment.
   * @param lane_marker The perceived lane markings.
   * @param path The converted navigation line segment.
   * @param is_mobileye  Whether the data source comes from the mobileye.
   * @return None.
   */
  void ConvertLaneMarkerToPath(perception::LaneMarkers* lane_marker,
                               common::Path* const path,
                               bool is_mobileye = true);
  bool LaneMarkerLogicalDecision(perception::LaneMarkers* lane_marker);
  bool CentralLaneDecision(perception::LaneMarkers* lane_marker,
                           perception::LaneMarker* right_marker,
                           perception::LaneMarker* left_marker);
  void RightLaneDecision(perception::LaneMarker* next_right_marker,
                         perception::LaneMarker* right_marker,
                         perception::LaneMarker* left_marker);
  void LeftLaneDecision(perception::LaneMarker* next_left_marker,
                        perception::LaneMarker* right_marker,
                        perception::LaneMarker* left_marker);
  void LanemarkerReverse(perception::LaneMarker* marker);
  void NoUseLanemarkerC2C3(perception::LaneMarkers* markers);
  void DigitalFilter(perception::LaneMarker* right_marker,
                     perception::LaneMarker* left_marker);
  void NextLanemarkerReverse(perception::LaneMarker* next_marker,
                             perception::LaneMarker* marker);
  bool JudgeHaveLanemarker(perception::LaneMarker* lane_marker);
  bool GenerateNeighborLanemarker(
      perception::LaneMarker* next_marker, perception::LaneMarker* marker,
      double width, std::deque<perception::LaneMarker>* lane_markers);
  double ComputeNoLanemarkerTime();
  int ComputeQuality(double ref_lanemarker_variance);
  bool CreatVirtualMarker(bool have_right, bool have_left,
                          perception::LaneMarker* right_lane_marker,
                          perception::LaneMarker* left_lane_marker);
  double ComputeLaneWidth(double* leftwidth);
  double ComputeLanemarkerQuality(
      std::deque<perception::LaneMarker>* lane_markers,
      const perception::LaneMarker& lanemarker);
  double ComputeLanemarkerStepQuality(
      const perception::LaneMarker& lanemarker,
      const perception::LaneMarker& history_lanemarker);
  bool SetRoutingAndRoad(TL::routing::RoutingResponse* inrouting,
                         TL::hdmap::Map* hd_map);
  /**
   * @brief Generate a lane centerline from the mobileye perceived lane
   * markings and convert it to a navigation line segment.
   * @param lane_marker The perceived lane markings.
   * @param path The converted navigation line segment.
   * @return None.
   */
  void ConvertMobileyeLaneMarkerToPath(
      const perception::LaneMarkers& lane_marker, common::Path* const path);
  void LogIndividualLanemarker(const perception::LaneMarkers& lane_marker);
  void LogAfterDecisionLanemarker(const perception::LaneMarkers& lane_marker);
  void InChangeLane(perception::LaneMarker* right_lane_marker,
                    perception::LaneMarker* left_lane_marker);
  /**
   * @brief Generate a lane centerline from the mobileye perceived lane markings
   * and convert it to a navigation line segment.
   *@param neta  neta includes mobileye info.
   * @param lane_marker The perceived lane markings.
   * @return True if neta info  is converted to the lane marker of
   * perception ; false otherwise.
   */

  /**
   * @brief Generate a lane centerline from the mobileye perceived lane markings
   * and convert it to a navigation line segment.
   * @param lane_marker The perceived lane markings.
   * @return True if chassis_detail info  is converted to the lane marker of
   * perception ; false otherwise.
   */

  void TranslatedReferenceLine(const perception::LaneMarkers& lane_marker,
                               const std::vector<Vec2d>& ref_line_point,
                               common::Path* const path,
                               const std::vector<Vec2d>& left_line_point,
                               const std::vector<Vec2d>& right_line_point,
                               hdmap::LineSegment* const left_path,
                               hdmap::LineSegment* const right_path);
  void BoundaryLineBus2Earth(const std::vector<Vec2d>& line_point,
                             hdmap::LineSegment* const path);
  double TruncateIntersectingBoundaryLines(
      const perception::LaneMarker& retain_lane_marker,
      const perception::LaneMarker& truncate_lane_marker);

 private:
  // the configuration information required by the `NavigationLaneMobileye`
  planning::PerceptionMapConfig config_;

  // received from topic: /apollo/lane_marker
  perception::LaneMarkers lane_marker_;

  // received from topic:/apollo/chassis_detail
  //   soc::ChassisDetail chassis_detail_;

  // navigation_path_list_ is a list of navigation paths. The internal paths
  // are arranged from left to right based on the vehicle's driving direction.
  // A navigation path is the combined results from perception and navigation.
  std::list<NaviPathTupleOld> navigation_path_list_{};

  // the navigation path which the vehicle is currently on.
  NaviPathTupleOld current_navi_path_tuple_{};

  // when invalid, left_width_ < 0
  double perceived_left_width_ = -1.0;

  // when invalid, right_width_ < 0
  double perceived_right_width_ = -1.0;

  // The standard lane width of China's expressway is 3.75 meters.
  double default_left_width_ = 1.875;
  double default_right_width_ = 1.875;
  double has_no_mobileye_lanemarker_time = 100.0;
  bool using_history_mapmsg_ = false;
  double start_no_lanemarker_time = 0.0;
  bool flag_log_no_lanemarker_time = false;
  double central_lanemarker_width_ = 3.75;
  double central_lanemarker_width_history_ = 3.75;
  int central_line_too_narrow_index = 0;
  // key: line index,
  // value: stitching index pair in the "key" line.
  std::unordered_map<int, StitchIndexPair> stitch_index_map_{};

  NaviLaneCentralConstructorOld navi_central_line_constructor_;
  // left and right central line history
  std::shared_ptr<navigation_hdmap::NavigationPath>
      right_central_navi_path_history_ =
          std::make_shared<navigation_hdmap::NavigationPath>();
  std::shared_ptr<navigation_hdmap::NavigationPath>
      left_central_navi_path_history_ =
          std::make_shared<navigation_hdmap::NavigationPath>();
  std::shared_ptr<hdmap::LineSegment> right_boundary_of_rightlane_history_ =
      std::make_shared<hdmap::LineSegment>();
  std::shared_ptr<hdmap::LineSegment> left_boundary_of_leftlane_history_ =
      std::make_shared<hdmap::LineSegment>();
  bool flag_using_history_left_centralline_ = false;
  bool flag_using_history_right_centralline_ = false;
  // neighbor lanemarker flag
  bool is_generate_left_neighbor_lanemarker = false;
  bool is_generate_right_neighbor_lanemarker = false;
  double left_neighbor_lanemarker_viewrange = 0.0;
  double right_neighbor_lanemarker_viewrange = 0.0;
  int using_left_neighbor_history_num = 0;
  int using_right_neighbor_history_num = 0;
  // Standard Deviation
  std::deque<perception::LaneMarker> left_lanemarker_variance_{};
  std::deque<perception::LaneMarker> right_lanemarker_variance_{};
  std::deque<perception::LaneMarker> left_neighbor_lanemarker_variance_{};
  std::deque<perception::LaneMarker> right_neighbor_lanemarker_variance_{};
  int variance_num_ = 5;
  bool in_change_lane_ = false;
  bool good_left_lane_quality_ = false;
  bool good_right_lane_quality_ = false;

  std::vector<Vec2d> central_line_pts_{};
  std::vector<Vec2d> left_central_line_pts_{};
  std::vector<Vec2d> right_central_line_pts_{};
  // It is used to transfer data acquired from perception to output layer,
  // only used as an intermediate variable
  perception::LaneMarker history_left_lanemarker_;
  perception::LaneMarker history_right_lanemarker_;
  perception::LaneMarker history_left_neighbor_lanemarker_;
  perception::LaneMarker history_right_neighbor_lanemarker_;
  perception::LaneMarkers history_lanemarkers_;
  navigation_hdmap::MapMsg history_map_msg_;
  std::shared_ptr<const common::VehicleState> vehicle_state_{nullptr};
  TL::common::DigitalFilter digital_filter_right_c2_;
  TL::common::DigitalFilter digital_filter_left_c2_;
  TL::common::DigitalFilter digital_filter_right_c3_;
  TL::common::DigitalFilter digital_filter_left_c3_;
  TL::common::MeanFilter mean_filter_;
};

// NOLINTEND
}  // namespace planning
}  // namespace TL
